// <auto-generated />
namespace Mohiuddin_EcommerceWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mohiuddinecommerce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mohiuddinecommerce));
        
        string IMigrationMetadata.Id
        {
            get { return "202406290836449_mohiuddin-ecommerce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
